In [1]:
import numpy as np

# Create a m x n integer array
m = 4
n = 3
arr = np.random.randint(10, size=(m, n))

# Print the array attributes
print("Array:\n", arr)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data Type:", arr.dtype)


Array:
 [[4 4 5]
 [9 6 1]
 [4 7 2]
 [1 1 3]]
Shape: (4, 3)
Dimensions: 2
Size: 12
Data Type: int32
